travis:
  secure:
    BINSTAR_TOKEN: ixdHS5eBPVv2/bsAwOscxHxZz7q7vVHqae/lHD83oUlyxH9YebpM//vEvEGE+0J3rHXgUxdr+mQkwtZTgaciY8cf7b8K2dfU7WmZMU1sDxz/TOCuzBCTI30QB0EsHU7aPgk5dXiFkBXlzLzxmDLf6zctj8vsK5Ns091HoZggUOYzt2G6rkCo0c8igBG7JBT6ULpEDSVXlANWHl5VnAwxJwfB0q93kYjtMr0SjYZKdBMsSltyPOU3h+z23P9VgnY30NaT7wWrhKVrQxk8wUY8qZ6z4DpSeWVgoMOpaLaAVQgmVC5+Z8+YLEU3KF5We5fRF6vF/V+gsXLnM4Hicf5qqDdL0YYzx4mjbJ+NnIqCeABYUYVQ13Qy0GJA9naAwhQYbSnALhiv6dXsaV+lAGAieGQHAv0NUogJ1W5UheyMCZXbN1rfqSr1KmFj2BfnlyahHmS/jknmmvOWBv86rJmqBmFRoR1Tqvol+nP4p+Ar98K+FbrChOPBkNqSnCSBhPCSq9AB4nRfs//yR1GgU9YHvMX9X0KHbxO32P2JUB7OOwAQC/wFO5O4jLDkkkU1Wr07FHRBanRNzKNwg41EOxLGQWeOEUbbhYbFJz48ldHRl+EbQBmL/je/iVK/easkQmtuMwvKbXka+uiWNKJ5yWAGSas7tH65UwvKcoPJBM5F2MQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
