travis:
  secure:
    BINSTAR_TOKEN: uvnM3f9f6XTt5YIq/RSq0zgLEPcVXI7eIwX88s5GVml/9FR+uElnd3Yl2xkMVcP2nEUhajs3/8eGbzebA5UPF+ucUga4KM8WHwviwg/9CchsB4q5u2X3vna2qTPi6uBD/KGZiJTaLFi1GoVjvT1CGpjnaPFu3OamGElt9RTHjHl2p5Q8u1z77lMS5/F9U/WPUpgxrJNNmWSBc4jrpXNR/upYFTj8DXn36P3eBXyo5HF9ZltJ49TAUFAizy39R3Oz4AzKCzSKASEROEkZIZH2C+iJDUb/CFD94wrSWuQ489w1HmAcyFmYqd49N6TzdBnB2yo2MOwxFh50g2Js3L+i39PSAXlrecj4teT6Yn92AalI8qPoExVC5mO8pt5PZCTlRQQOZt9wGJtdWBgZdxNY3BJvMC6nAK0hOVFZqYzOzc86qHnq4XFk0oLj9kjQB6SNtf6djz00IigZ6x/pM6dTtvKAFCD0K3zVYsrGXK2A0QKZZ/bmANtfjxNCJrBL2G7d9rUDBrToflw1/sNauOQrt267Jh4DpWR2LNltIkaZ58y6g2ncP0SIrtvi35WQdO/coAnz2RSxea8+L3z7UVhWZF5n7A29spgh5yAEUGdaxVg8jaRmkJBkAMB8Tx/EMKaKfk5QQ7+hIbIjrR66oPDlyGdqP4SN4vX8RGD69jz2+QI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
